repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'conda list --export > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [pre-commit]